course = 'Python for Beginners'
print(course)
print(course.upper())
print(course.lower())
print(course.find('Beginners'))
print(course.replace('Beginners', 'Absolute Beginners'))
print(course.replace('P', 'J'))
print('python' in course)
print(course.title())
# len()